apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base
  - ingress.yaml
  - secrets.yaml
  - network-policy.yaml

patches:
  - target:
      kind: Deployment
      name: crypto-bot-backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: registry.gitlab.com/dst_crypto/crypto-bot-app/backend:staging
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENVIRONMENT
          value: staging
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DEBUG
          value: "true"
      - op: add
        path: /spec/template/metadata/annotations
        value:
          deployed-commit: "66fb41a4"

  - target:
      kind: Deployment
      name: crypto-bot-frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: registry.gitlab.com/dst_crypto/crypto-bot-app/frontend:staging
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENVIRONMENT
          value: staging
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: APP_VERSION
          value: 66fb41a4
      - op: add
        path: /spec/template/metadata/annotations
        value:
          deployed-commit: "66fb41a4"