---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCnYy58SaItXqFUkA/LrTqLGPYmSzs4MhU33iH0x89AZQXMZWs5LXNs9/zQP8dXJ0GwL3CSiu7dSoNrJ55Hj733/Zsu0VFKj43+qzZCCfNKcGkEwfxtpZUksQkrYFjDAK69LmcOeJ6+qrTQI0/4WwCb78fI1yuScWLkoT9423eAZom4KJFYiM0yF1VdAEMmwt5vfrBANtThCXFBFCL5Nw44PzoISf768EJeG+dJFWCmBTys0q0pMdtLhDvQi7CwsfadNHTg9Q6viNAZ7t/mlljEMv495XbvWNduq2sqh174izmbUrLqF4wd//E+zBw+41nNh7+EqLqqmHk1L1cbox10EkAe7zsznruM4t0JZ4Dt+sWj23Ye4u/wFsP23fES6yREtMhxsVzYqI3JD7PeHJlmIX+/60Ty9Y3Zwofvph69IBKvonSiCmDvsugc1RKL7k7wfxTq3A0qN24D8yuXvU+MmsrXNRgxBZhk7atRCMXaWU/yAss4LtjcKGYn9CoOLhRqnFUkmJN2ZoiKq3TTLIwqqwwY3txzclMoKSuYw4TKH1HFyrTpSlV5zmv5ntpEwTDUbgaO2A849vf3gSCKdtIv0IWcnHMfLzcgYChE8D6yYDenGnmQFHYzGEP3bGOfMF2ro/l5N7+idJSCoqrOnzC2zDmdTOA7bSwPNXZ2YAuhTG5s5ykC6Yg6ZPqGnIkSA6jYwIIp8/vQowgMFRHezga3GQQ8o8qJ7lSKbejZzgF62g==
    admin-user: AgBBarlfKb8C+EKWlyIgeoKGyr+C0DyLZN0TWBTDwnk4JwmMtXU3ZTfHVGytBis+/+4ech5Hm1YFFP3xJv5oE/JYKAGkLowpCMAcB2AB9nTAc7IYk89Ji8K2olZc1FFmFkpMjcjHLy1EdMGM9i+bnjAMMgVLc23kLeBc8r1R8e3uSkpOWgxg5db0zux/x53cxoS/cuSmwthusromMIJwmCY8vBaZaMYZAy+KQxMTUmqeVEDA+HuiJGzOr7Fptb9USBZPyfah5HsxMKOdfpsTBJtDW5A+NKq26bVscTcjC5CPGhjuBBsJ/qFrCyz6iVApPS6LTXFgBRyB5xZdOyCwqUzd8Cdsbht1e7mS8uNk5nMX7iB/f0VWX4pocu8aUkcc2MEc7SZC6BrWHjTDhJU9p88Y2Rt5/fkWq3g6SvfvRxT/V2SgVm7K8FYVy8VMzri2lV3aRU2T33hKTX/AIr8q9WAnVTCZIItpeE4VPOx72fCP34oZQ2/RvYUgEp6eqVOp1LT4Hf6Ia2zhXyxscP0GbeenSmH3NRoiJzqS8DOyGqt4W60sPaIshTzVClM4Ba419W4Gnl4ubWGSbg5okCMxvXhkS0/OHAVxTD5xYxhP+Wq3zdGBJ6aCkNFGsEoCN88AEtvLb57SisQ0pIDW8GscptPcSqcXyUJXE5OTbWWLI5QFuOZm7Eo7P8SmZpt7rxJOOpV/21MQuQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: Opaque
