apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-admin-sealed.yaml
  - grafana-dashboard-crypto-bot.yaml
  - grafana-dashboard-infra.yaml
  - loki-ingress.yaml
  - grafana-ingress.yaml
  - grafana-postgres-creds-sealed.yaml
  - alertmanager-smtp-sealed.yaml
  - tailscale-proxy.yaml
  - tailscale-proxy-auth-sealed.yaml
